# Generated by Django 3.0.5 on 2020-04-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('dateofbirth', models.DateField()),
                ('email', models.TextField(max_length=40)),
                ('username', models.CharField(max_length=30)),
                ('password', models.TextField(max_length=30)),
                ('repeat_password', models.TextField(max_length=30)),
            ],
        ),
    ]
